apiVersion: v1
kind: Service
metadata:
  name: my-next-app-service
spec:
  selector:
    app: my-next-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
